### ISSUE TITLE
ticket module still not downloading

### ISSUE THREAD

**Issue by Bebiano86** [oNdsen/OGP-AdminLTE#1]
Download still not working after commits 2d2c8b5

I already cleared the cache. It loads the console.log("reloaded body scripts");

**Comment by oNdsen** [comment]
Sorry for the late Reply @Bebiano86 i was really busy. Just checked and must had something in the Cache, because i just realized that Commit could not work. I need to reload after Dom modification. Please check the newest commit: f473c5e6bb6530c526ad4b151fe141f1a2aab7dc

**Comment by Bebiano86** [comment]
it seems that everything works ;)

I'll test everything for a few days then I'll give feedback

**Comment by Bebiano86** [comment]
everything seems to be working perfectly
