### ISSUE TITLE
text area news module does not work

### ISSUE THREAD

**Issue by Bebiano86** [oNdsen/OGP-AdminLTE#2]
text area when you are doing a big news does not follow the text!
in the admin area.

**Comment by oNdsen** [comment]
can you give me more details with an example please? thanks!

**Comment by Bebiano86** [comment]
yes I leave an image below
![Sem Título](https://user-images.githubusercontent.com/15680365/229190544-316ce8b0-60a7-459f-b9db-1df5e44050c4.png)

**Comment by oNdsen** [comment]
i just took a look at the module and noticed, that an overflow attribute was missing.
just added it: 3807a146b7433ded5cd57820431367b1a56c2d0b
can you please verify @Bebiano86 ?
thanks

**Comment by Bebiano86** [comment]
it's working perfectly

**Comment by Bebiano86** [comment]
We can't put the text area with the size we want?
example
![Sem Título](https://user-images.githubusercontent.com/15680365/229608840-440f1bfb-c8ca-4199-b8f6-851058be6985.png)

**Comment by oNdsen** [comment]
> We can't put the text area with the size we want? example ![Sem Título](https://user-images.githubusercontent.com/15680365/229608840-440f1bfb-c8ca-4199-b8f6-851058be6985.png)

this is because of the plugin initiation in the news module. there is a missing parameter on tinymce.init{}.
see tinymce documentation: https://www.tiny.cloud/docs/tinymce/6/editor-size-options/
